### ISSUE TITLE
Difference only works on shapes and not paths

### ISSUE THREAD

**Issue by k2OS** [Moini/inkscape-extensions-multi-bool#1]
I came to this plugin as I am looking for a simple way of cutting a _lot_ of parallel lines with a shape (to end up with a line art representation of the original shape).

Currently, contrary to what I would have thought, the 'intersect' tool in Inscape only works on shapes and not paths... someone then pointed me to this plugin, that's listed as also being able to work on paths, and even though there is no intersect function, I had the idea that I could implement this myself from the Difference function...

But alas - this plugin doesn't work on paths either, even though it's described as being able to do so.. am I missing something?

**Comment by Moini** [comment]
The 'intersect' boolean operation (just like all boolean operations) in Inkscape works on both shapes and paths.
This extension, too, works on paths as well as shapes, as it is based on that same Inkscape functionality.
Maybe there are clones, or a group in your selection? If so, unlink any clones and ungroup any groups.

Neither the extension, nor the boolean operations in Inkscape work with groups or clones.

'Intersect' would probably be easy to implement, yes.

**Comment by Moini** [comment]
Btw. you can also use the standard boolean operation for this, if the parallel lines all have the same color. Then you just need to combine the lines before cutting them.
Or, if the purpose of the image is just to be exported to png, and not to be used for a cutting machine, you could use a clip.

**Comment by k2OS** [comment]
Hmm retrying, the 'cut' extension actually does work, No idea why it didn't before (both yours and the builtin does..).

"The 'intersect' boolean operation (just like all boolean operations) in Inkscape works on both shapes and paths.".

Oh how I wish this was true (for horizontal lines).

Make a box, convert it to path, Draw a line with the bezier tool - a horizontal line, with just 2 nodes (the line has to be wider  than the box). Place the box over the line, move the line to the bottom of the stack, move the box to the top. Do Path -> Intersect and both the line and the box disappears in a puff of smoke. This happens with both your extension and the builtin function.

It is true, however, that it works if the path I intersect on isn't a straight line, but this is not what i need.

**Comment by Moini** [comment]
The intersection boolop is for intersecting fills. A straight line's fill has an area of 0, so there's nothing that would intersect. 

What you want is to either turn the stroke to path first, so you can intersect areas.

Or you can use 'Cut path' and remove the cut-off parts manually (this will split the path, you may not be able to see the cuts, but drag on something and you'll see it's a separate object).

**Comment by k2OS** [comment]
Yeah, I understand now that the boolean operations only play nice with shapes.

My issue is that I want to create a set of lines (just lines, not shapes, as I want to draw these on a plitter) that has been cut with a rather complex shape, leaving me with a _multitude_ of little line pieces that I have to remove manually afterwards (after usig Cut Paths). What I was hoping for, was that there would be a way for Inkscapte to produce something that resembles what I get when using Clip.

Cheers

**Comment by Moini** [comment]
Okay, so what you mean by 'shape' is a filled path? In Inkscape, shapes are: rectangles, stars, polygons, spirals, ellipses. Maybe that was the source of the misunderstanding.

No, that's currently not possible directly for straight lines, as far as I know. 

However, you could use hatching that is produced by several different extensions, for exactly this purpose.

Or you can do a centerline trace of a bitmap copy of a clipped version of the image. Sounds complex, but is fast.

Or you can use an LPE (stitch subpaths), to get this result (but the density of the subpaths will depend on path's slope).

**Comment by k2OS** [comment]
Yes! Finally something I can use :D I did think about the posibility of doing centerline trace (I did not know it was called that), but couldn't remember seeing something like that in Inkscape - and for a good reason.
It's something to move on with and I am sure it will result results. Thank you very much :)

**Comment by Moini** [comment]
It's not in Inkscape, you need to install it first.
Find it here: https://github.com/fablabnbg/inkscape-centerline-trace

**Comment by Moini** [comment]
I'm archiving this repository now, it moved to https://gitlab.com/Moini/inkscape-extensions-multi-bool/ . If there's anything left to do here, please open a new report over there.
