### ISSUE TITLE
crash on recent trunk, Windows

### ISSUE THREAD

**Issue by alvinpenner** [Moini/inkscape-extensions-multi-bool#2]
thank you very much for these extensions! I have been using them as a basis for a proposal of my own. 
https://bugs.launchpad.net/inkscape/+bug/1662531
When I run these extensions on recent Windows trunk, I get the attached crash message
![multipledivision](https://cloud.githubusercontent.com/assets/17321324/23073688/59a00d4e-f504-11e6-973c-ecaa0effc465.png)

I was able to fix it by adding the line 
        inkex.os.environ['LC_ALL'] = 'C' # pass this to the spawned Inkscape
before calling Popen.

Cheers,
Alvin

**Comment by Moini** [comment]
Oooh. That doesn't look cool. 

Now the question is: is this a bug in trunk that needs to be fixed, or is it a problem with the extension? It appears that the same workaround had to be used for the line-height fixing script, so it doesn't mess up the lineheights more than it did before. The thing is, it worked before, so it may be an issue with Inkscape itself. It could just set a locale when called without a valid one, for example.

Do you happen to know more about the reasons, so we can decide whether this change will be needed?

I don't have a recent trunk version here, but I will definitely need to review and test this before the 0.93 release.

**Comment by alvinpenner** [comment]
as far as I know, it was introduced in rev 15444
http://bazaar.launchpad.net/~inkscape.dev/inkscape/trunk/revision/15444
but it is not a bug in Inkscape. It is a requirement that there must be a valid locale
https://bugs.launchpad.net/inkscape/+bug/1662531/comments/28
https://bugs.launchpad.net/inkscape/+bug/1662531/comments/29
so I patched it by setting the variable LC_ALL.
It is possible this may be a Windows-only bug.
I believe it came about because this Inkscape rev introduced a degree symbol (°) in a new spin box

**Comment by Moini** [comment]
Thank you, Alvin. I commented on the bug report on lp now. 
I'd rather see this fixed in Inkscape than in all the extensions out there, and I don't think it would be a good idea to have Windows users set environment variables before they can use Inkscape via command line.
(at least this is what I understood it means).

**Comment by Moini** [comment]
@alvinpenner I'm archiving this repository now, it moved to https://gitlab.com/Moini/inkscape-extensions-multi-bool/ . I'd recommend using V's version of the extension, though: https://gitlab.com/su-v/inx-pathops
